theme = "ayu_light"
# theme = "catppuccin_latte"
# theme = "catppuccin_mocha"

[editor]
true-color = true
auto-format = true

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true
