[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "python"
auto-format = true

[[language]]
name = "nix"
formatter = { command = "alejandra" }
auto-format = true

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "clojure"
auto-format = true
