[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "python"
auto-format = true

[[language]]
name = "nix"
formatter = { command = "nixfmt" }
auto-format = true

[[language]]
name = "toml"
auto-format = true

